/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ApiResponseStatsByCategoryDTO } from '../model/apiResponseStatsByCategoryDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class StatisticsService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get stats by main category
     * 
     * @param accountId 
     * @param dateMin 
     * @param dateMax 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getStatsByMainCategory(accountId: number, dateMin: string, dateMax: string, observe?: 'body', reportProgress?: boolean): Observable<ApiResponseStatsByCategoryDTO>;
    public getStatsByMainCategory(accountId: number, dateMin: string, dateMax: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ApiResponseStatsByCategoryDTO>>;
    public getStatsByMainCategory(accountId: number, dateMin: string, dateMax: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ApiResponseStatsByCategoryDTO>>;
    public getStatsByMainCategory(accountId: number, dateMin: string, dateMax: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (accountId === null || accountId === undefined) {
            throw new Error('Required parameter accountId was null or undefined when calling getStatsByMainCategory.');
        }

        if (dateMin === null || dateMin === undefined) {
            throw new Error('Required parameter dateMin was null or undefined when calling getStatsByMainCategory.');
        }

        if (dateMax === null || dateMax === undefined) {
            throw new Error('Required parameter dateMax was null or undefined when calling getStatsByMainCategory.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ApiResponseStatsByCategoryDTO>('get',`${this.basePath}/api/stats/${encodeURIComponent(String(accountId))}/${encodeURIComponent(String(dateMin))}/${encodeURIComponent(String(dateMax))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
